# Generated by Django 3.0.3 on 2020-02-21 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitation', '0002_auto_20200211_2020'),
    ]

    operations = [
        migrations.AddField(
            model_name='invite',
            name='slug',
            field=models.CharField(default='56692649-7aa3-4fbf-b8c3-f41e595084e5', max_length=36),
        ),
    ]
