# Generated by Django 3.1.2 on 2020-10-10 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitation', '0003_invite_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitetemplate',
            name='body_size',
            field=models.PositiveIntegerField(default=70, verbose_name='Tamanho do texto'),
        ),
        migrations.AddField(
            model_name='invitetemplate',
            name='title_size',
            field=models.PositiveIntegerField(default=170, verbose_name='Tamanho do título'),
        ),
        migrations.AlterField(
            model_name='invite',
            name='slug',
            field=models.CharField(default='3003b7bb-8af9-4d74-8746-d6b3be158b5b', max_length=36),
        ),
    ]
