# Generated by Django 3.1.2 on 2020-10-10 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitation', '0004_auto_20201010_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitetemplate',
            name='body_pos',
            field=models.PositiveIntegerField(default=800, verbose_name='Posição do texto'),
        ),
        migrations.AddField(
            model_name='invitetemplate',
            name='title_pos',
            field=models.PositiveIntegerField(default=600, verbose_name='Posição do título'),
        ),
        migrations.AlterField(
            model_name='invite',
            name='slug',
            field=models.CharField(default='5ab43c30-09f3-4ca2-bd27-237ef17b2625', max_length=36),
        ),
    ]
