# Generated by Django 3.1.2 on 2020-10-10 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitation', '0005_auto_20201010_1154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invite',
            name='gender',
        ),
        migrations.AlterField(
            model_name='invite',
            name='slug',
            field=models.CharField(default='61c5fa8e-e4a7-4873-868b-7595acf8013d', max_length=36),
        ),
    ]
