# Generated by Django 3.2.3 on 2021-05-13 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitation', '0006_auto_20201010_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestinvite',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='invite',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='invite',
            name='slug',
            field=models.CharField(default='f4573b5b-fee7-4055-8a64-df8cd4c00840', max_length=36),
        ),
        migrations.AlterField(
            model_name='invitecategory',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='invitetemplate',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
